name: Pull Request


on:
  push:
    branches:
    - renovate/**
  pull_request:
    branches:
    - main


env:
  PYTHON: python


jobs:
  cancel_previous:
    name: 'Cancel Previous Runs'
    runs-on: ubuntu-22.04
    timeout-minutes: 3

    steps:
    - uses: ydataai/cancel-workflow-action@0.7.0
      with:
        ignore_sha: true
        access_token: ${{ secrets.ACCESS_TOKEN }}


  validate:
    name: Validate
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements-dev.txt
        python -m pip install ydata-core

    - name: Lint
      run: make lint PYTHON=$PYTHON

    - name: Test
      run: make test PYTHON=$PYTHON
