name: Pull Request


on:
  pull_request:
    branches:
    - main


env:
  PYTHON: python


jobs:
  cancel_previous:
    name: 'Cancel Previous Runs'
    runs-on: ubuntu-20.04
    timeout-minutes: 3

    steps:
    - uses: ydataai/cancel-workflow-action@0.7.0
      with:
        ignore_sha: true
        access_token: ${{ secrets.ACCESS_TOKEN }}


  validate:
    name: Validate
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Lint
      run: make lint PYTHON=$PYTHON
