name: Releases



on:
  release:
    types:
    - released



jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-22.04

    outputs:
      version: ${{ steps.version.outputs.value }}

    steps:
    - name: Version
      id: version
      run: echo "value=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT


  build-packages:
    name: Build ${{ matrix.package }} package
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        package: [core, datascience]

    needs:
    - prepare

    env:
      ROOT_DIR: src/${{ matrix.package }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install build dependencies
      run: python -m pip install --upgrade pip wheel

    - name: Build
      run: |
        make build-${{ matrix.package }} version=${{ needs.prepare.outputs.version }} PYTHON=python

    - name: Upload release assets
      uses: AButler/upload-release-assets@v3.0
      with:
        files: '${{ env.ROOT_DIR }}/dist/*'
        repo-token: ${{ secrets.ACCESS_TOKEN }}
        release-tag: ${{ needs.prepare.outputs.version }}

    - name: Upload package to pypi
      uses: pypa/gh-action-pypi-publish@v1.9.0
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        packages_dir: '${{ env.ROOT_DIR }}/dist/'

  # update-dockerfiles:
  #   name: Create pull request to update dockerfiles
  #   runs-on: ubuntu-22.04

  #   needs:
  #   - prepare
  #   - build-dask
  #   - build-platform-common
  #   - build-platform-dask
  #   - build-platform-datasources
  #   - build-platform-synthesizers

  #   env:
  #     VERSION: ${{ needs.prepare.outputs.version }}

  #   steps:
  #   - name: Checkout repo
  #     uses: actions/checkout@v3
  #     with:
  #       repository: ydataai/dockerfiles
  #       token: ${{ secrets.ACCESS_TOKEN }}

  #   - name: Update python base requirements file
  #     env:
  #       FILE: data-science/python_ydata_base/requirements-ydata.txt
  #     run: |
  #       sed -i -r 's|\ydata-dask==.*|ydata-dask==${{ env.VERSION }}|g' ${{ env.FILE }}
  #       sed -i -r 's|\ydata-platform-common==.*|ydata-platform-common==${{ env.VERSION }}|g' ${{ env.FILE }}
  #       sed -i -r 's|\ydata-platform-dask==.*|ydata-platform-dask==${{ env.VERSION }}|g' ${{ env.FILE }}
  #       sed -i -r 's|\ydata-platform-datasources==.*|ydata-platform-datasources==${{ env.VERSION }}|g' ${{ env.FILE }}
  #       sed -i -r 's|\ydata-platform-synthesizers==.*|ydata-platform-synthesizers==${{ env.VERSION }}|g' ${{ env.FILE }}

  #   - name: Create Pull Request
  #     uses: peter-evans/create-pull-request@v3
  #     with:
  #       token: ${{ secrets.ACCESS_TOKEN }}
  #       branch: chore/bump-platform-python-sdk
  #       branch-suffix: random
  #       delete-branch: true
  #       commit-message: "chore(deps): bump platform-python-sdk to version ${{ env.VERSION }}"
  #       committer: "Azory <azory@ydata.ai>"
  #       title: "chore(deps): bump platform-python-sdk to version ${{ env.VERSION }}"
  #       body: https://github.com/ydataai/platform-python-sdk/releases/tag/${{ env.VERSION }}
  #       author: "Azory <azory@ydata.ai>"
  #       reviewers: portellaa
  #       team-reviewers: backend
  #       labels: ci,platform-python-sdk


  # update-integration-tool:
  #   name: Create pull request to update integration tool
  #   runs-on: ubuntu-22.04

  #   needs:
  #   - prepare
  #   - build-dask
  #   - build-platform-common
  #   - build-platform-dask
  #   - build-platform-datasources
  #   - build-platform-synthesizers

  #   env:
  #     VERSION: ${{ needs.prepare.outputs.version }}

  #   steps:
  #   - name: Checkout repo
  #     uses: actions/checkout@v3
  #     with:
  #       repository: ydataai/ydata-lib-platform-integration-tool
  #       token: ${{ secrets.ACCESS_TOKEN }}

  #   - name: Update requirements file
  #     env:
  #       FILE: requirements.txt
  #     run: |
  #       sed -i -r 's|\ydata-dask==.*|ydata-dask==${{ env.VERSION }}|g' ${{ env.FILE }}
  #       sed -i -r 's|\ydata-platform-common==.*|ydata-platform-common==${{ env.VERSION }}|g' ${{ env.FILE }}
  #       sed -i -r 's|\ydata-platform-dask==.*|ydata-platform-dask==${{ env.VERSION }}|g' ${{ env.FILE }}
  #       sed -i -r 's|\ydata-platform-datasources==.*|ydata-platform-datasources==${{ env.VERSION }}|g' ${{ env.FILE }}
  #       sed -i -r 's|\ydata-platform-synthesizers==.*|ydata-platform-synthesizers==${{ env.VERSION }}|g' ${{ env.FILE }}

  #   - name: Create Pull Request
  #     uses: peter-evans/create-pull-request@v4
  #     with:
  #       token: ${{ secrets.ACCESS_TOKEN }}
  #       branch: chore/bump-platform-python-sdk
  #       branch-suffix: random
  #       delete-branch: true
  #       committer: "Azory <azory@ydata.ai>"
  #       commit-message: "chore(deps): bump platform-python-sdk to version ${{ env.VERSION }}"
  #       title: "chore(deps): bump platform-python-sdk to version ${{ env.VERSION }}"
  #       body: https://github.com/ydataai/platform-python-sdk/releases/tag/${{ env.VERSION }}
  #       author: "Azory <azory@ydata.ai>"
  #       reviewers: portellaa
  #       team-reviewers: backend
  #       labels: ci,platform-python-sdk
